version: 2
jobs:
  deploy_staging:
    docker:
      - image: govau/cf-cli
    working_directory: /app
    steps:
      - checkout
      - run: cf login -a $CF_STAGING_API -u $CF_STAGING_USER -p $CF_STAGING_PASSWORD -o dta -s govau
      - run: cf zero-downtime-push gov-au-beta-static -f manifest.yml -p ./www
  deploy_prod:
    docker:
      - image: govau/cf-cli
    working_directory: /app
    steps:
      - checkout
      - run: cf login -a $CF_PROD_API -u $CF_PROD_USER -p $CF_PROD_PASSWORD -o dta -s govau
      - run: cf zero-downtime-push gov-au-beta-static -f manifest.yml -p ./www

workflows:
  version: 2
  deploy:
    jobs:
      - deploy_staging
          # filters:
          #   branches:
          #     only: /^master$/
      - deploy_prod:
          filters:
            branches:
              ignore:
                /.*/
            tags:
              only: /release-.*/
